name: Build ffviewer

on: [push]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2.1.1

    - name: Build project for Windows x86_64
      run: |
        GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC="zig cc -target x86_64-windows-gnu" go build -o ./bin/win/64/ffviewer.exe

    - name: Build project for Linux x86_64
      run: |
        GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o ./bin/linux/64/ffviewer

    - name: Upload Linux x86_64 binary
      uses: actions/upload-artifact@v3
      with:
        name: ffviewer-linux-x86_64
        path: ./bin/linux/64/ffviewer

    - name: Upload Windows x86_64 binary
      uses: actions/upload-artifact@v3
      with:
        name: ffviewer-windows-x86_64
        path: ./bin/win/64/ffviewer.exe
